In [55]:
from Bio import SeqIO
from pathlib import Path
import os
import pandas as pd
import parse_fasta as pf
import numpy as np
import polars as pl
import obonet
import re

Process proteins per phage into dataframe

In [56]:
base_path = Path("../data")

proteins_path = base_path / "proteins"

data = []
for file in proteins_path.iterdir():
    for record in pf.parse_fasta(file):
        data.append([file.stem, record.id, str(record.seq), record.description])

data_df = pd.DataFrame(
    data, columns=["phage_id", "protein_id", "sequence", "description"]
)

# drop e.coli pseudo genes
data_df = data_df.replace("None", pd.NA)
data_df = data_df.dropna()

print("Total proteins: ", len(data_df))
data_df.head()

Total proteins:  20186

,phage_id,protein_id,sequence,description
0,MZ501058,QXV77207.1,MANDVLVPDLMSPEGMDVIEAYLQCGSDVPSAARSLGMSGIAFRDI...,terminase small subunit
1,MZ501058,QXV77208.1,MEVSRPYVNTVDVIDFGIDKRFFRLPVSGILAQEGITPNGPQIAII...,terminase large subunit
2,MZ501058,QXV77209.1,MASNIKYKRDAISLMRDGIKSQYKKDSQCAICGCAEELELHHYHTV...,nicking endonuclease
3,MZ501058,QXV77210.1,MGFKSWITEKLNPGQRIIRDMEPVSHRTNRKPFTTGQAYNKIEILN...,portal protein
4,MZ501058,QXV77211.1,MIDYNGLKTIFGEKLPESHIFFATVAAHKYVPSYAFLRRELGLSSA...,head decoration protein

Write proteins to fasta

In [57]:
fasta_file = "../data/interpro/interpro_sequences.fasta"
with open(fasta_file, "w") as outfile:
    for index, row in data_df.iterrows():
        protein_id = row["protein_id"]
        sequence = row["sequence"]
        outfile.write(f">{protein_id}\n{sequence}\n")

data_df[["protein_id", "sequence"]].to_csv(
    "../data/protein_sequences.tsv", sep="\t", index=False
)

Run Interproscan: ./interproscan.sh -i data/interpro/interpro_sequences.fasta -b data/interpro/

Load interproscan results

In [58]:
interpro_path = "../data/interpro/interpro_sequences.fasta.tsv"

interpro_df = pd.read_csv(interpro_path, sep="\t", header=None)

column_names = [
    "protein_id",
    "Sequence MD5 Digest",
    "Sequence Length",
    "Analysis",
    "Signature Accession",
    "Signature Description",
    "Start Location",
    "Stop Location",
    "Score",
    "Status",
    "Date",
    "accession",
    "InterPro Annotation Description",
    "GO Annotations",
    "Pathways annotations",
]

interpro_df.columns = column_names
interpro_df.head()

,protein_id,Sequence MD5 Digest,Sequence Length,Analysis,Signature Accession,Signature Description,Start Location,Stop Location,Score,Status,Date,accession,InterPro Annotation Description,GO Annotations,Pathways annotations
0,QXV79977.1,92daf1ebaddf57a88018569c5a5052e1,197,Pfam,PF06941,"5' nucleotidase, deoxy (Pyrimidine), cytosolic...",1,175,0.027,T,09-07-2025,IPR010708,5'(3')-deoxyribonucleotidase,-,-
1,QXV79977.1,92daf1ebaddf57a88018569c5a5052e1,197,Gene3D,G3DSA:3.40.50.1000,-,61,197,9.7E-15,T,09-07-2025,IPR023214,HAD superfamily,-,-
2,QXV79977.1,92daf1ebaddf57a88018569c5a5052e1,197,SUPERFAMILY,SSF56784,HAD-like,2,194,3.35E-10,T,09-07-2025,IPR036412,HAD-like superfamily,-,-
3,NP_416254.1,ea37cb76b651f90db9b8d4dbf6861145,275,NCBIfam,NF001979,ammonia-dependent NAD(+) synthetase,1,274,0.0,T,09-07-2025,-,-,-,-
4,NP_416254.1,ea37cb76b651f90db9b8d4dbf6861145,275,Hamap,MF_00193,NH(3)-dependent NAD(+) synthetase [nadE].,18,268,47.316956,T,09-07-2025,IPR022926,NH(3)-dependent NAD(+) synthetase,-,-

In [59]:
# Clean dataframe
print("Before: ", len(interpro_df), " entries")

interpro_df = interpro_df[["protein_id", "accession"]].drop_duplicates()

interpro_df.reset_index(drop=True, inplace=True)

interpro_df = interpro_df.replace("-", pd.NA).dropna()

print("After: ", len(interpro_df), " entries")
interpro_df.head()

Before:  72862  entries
After:  32362  entries

    protein_id  accession
0   QXV79977.1  IPR010708
1   QXV79977.1  IPR023214
2   QXV79977.1  IPR036412
4  NP_416254.1  IPR022926
5  NP_416254.1  IPR014729

Cluster based on interpro accessions

In [60]:
unique_accessions = (
    interpro_df.groupby("accession")["protein_id"].apply(list).reset_index()
)

unique_accessions.head()

   accession                                         protein_id
0  IPR000014  [NP_415801.1, NP_416571.1, NP_417345.1, YP_026...
1  IPR000015  [NP_415065.1, NP_414681.1, NP_415460.1, NP_417...
2  IPR000021  [NP_416080.1, YP_026229.1, NP_414559.1, YP_025...
3  IPR000023                                      [NP_418351.1]
4  IPR000031                                      [NP_415056.1]

In [61]:
len(unique_accessions["protein_id"][0])

14

# Potential binary vector for interpro signatures here

In [62]:
# ...

Load Interpro to GO list

In [63]:
ip2go = []
with open("../data/interpro/interpro2go", "r") as index:
    for row in index:
        row = row.strip()

        if row.startswith("!"):
            continue

        items = row.split("InterPro:")[1].split(" > ")

        ip_accession = items[0].split(" ")[0]
        ip_term = " ".join(items[0].split(" ")[1:])

        go_items = items[1].split(";")
        go_term = go_items[0].strip().replace("GO:", "")
        go_accession = go_items[1].strip()

        ip2go.append([ip_accession, ip_term, go_accession, go_term])

ip2go_df = pd.DataFrame(
    ip2go,
    columns=[
        "Interpro accession",
        "Interpro description",
        "GO accession",
        "GO description",
    ],
)
ip2go_df.head()

,Interpro accession,Interpro description,GO accession,GO description
0,IPR000003,Retinoid X receptor/HNF4,GO:0003677,DNA binding
1,IPR000003,Retinoid X receptor/HNF4,GO:0003707,nuclear steroid receptor activity
2,IPR000003,Retinoid X receptor/HNF4,GO:0008270,zinc ion binding
3,IPR000003,Retinoid X receptor/HNF4,GO:0006355,regulation of DNA-templated transcription
4,IPR000003,Retinoid X receptor/HNF4,GO:0005634,nucleus

Mark ribosome-related entries

In [64]:
ribosome_keywords = [
    "ribosome",
    "ribosomal",
    "rRNA binding",
    "translation",
    "structural constituent of ribosome",
]

ip2go_df["ribosome"] = ip2go_df["GO description"].str.contains(
    "|".join(ribosome_keywords), case=False, na=False
)
ip2go_df[ip2go_df["ribosome"]].head()

,Interpro accession,Interpro description,GO accession,GO description,ribosome
41,IPR000039,Large ribosomal subunit protein eL18,GO:0003735,structural constituent of ribosome,True
42,IPR000039,Large ribosomal subunit protein eL18,GO:0006412,translation,True
43,IPR000039,Large ribosomal subunit protein eL18,GO:0005840,ribosome,True
62,IPR000054,Large ribosomal subunit protein eL31,GO:0003735,structural constituent of ribosome,True
63,IPR000054,Large ribosomal subunit protein eL31,GO:0006412,translation,True

#### Assign GO-terms to proteins

Add root Go-term to all GO-terms

In [65]:
graph = obonet.read_obo("../data/interpro/go-basic.obo")

# Create a mapping dict: GO ID -> namespace
go_to_namespace = {
    go_id: data.get("namespace") for go_id, data in graph.nodes(data=True)
}

# Map it to your dataframe
ip2go_df["namespace"] = ip2go_df["GO accession"].map(go_to_namespace)
ip2go_df.head(10)

,Interpro accession,Interpro description,GO accession,GO description,ribosome,namespace
0,IPR000003,Retinoid X receptor/HNF4,GO:0003677,DNA binding,False,molecular_function
1,IPR000003,Retinoid X receptor/HNF4,GO:0003707,nuclear steroid receptor activity,False,molecular_function
2,IPR000003,Retinoid X receptor/HNF4,GO:0008270,zinc ion binding,False,molecular_function
3,IPR000003,Retinoid X receptor/HNF4,GO:0006355,regulation of DNA-templated transcription,False,biological_process
4,IPR000003,Retinoid X receptor/HNF4,GO:0005634,nucleus,False,cellular_component
5,IPR000006,"Metallothionein, vertebrate",GO:0046872,metal ion binding,False,molecular_function
6,IPR000009,Protein phosphatase 2A regulatory subunit PR55,GO:0019888,protein phosphatase regulator activity,False,molecular_function
7,IPR000009,Protein phosphatase 2A regulatory subunit PR55,GO:0000159,protein phosphatase type 2A complex,False,cellular_component
8,IPR000010,Cystatin domain,GO:0004869,cysteine-type endopeptidase inhibitor activity,False,molecular_function
9,IPR000011,Ubiquitin/SUMO-activating enzyme E1-like,GO:0008641,ubiquitin-like modifier activating enzyme acti...,False,molecular_function

Cluster GO accessions for Interpro accessions

In [66]:
ip2go_grouped = ip2go_df.groupby("Interpro accession")["GO accession"].apply(list)

ip2go_grouped.head()

Interpro accession
IPR000003    [GO:0003677, GO:0003707, GO:0008270, GO:000635...
IPR000006                                         [GO:0046872]
IPR000009                             [GO:0019888, GO:0000159]
IPR000010                                         [GO:0004869]
IPR000011                             [GO:0008641, GO:0036211]
Name: GO accession, dtype: object

In [67]:
unique_accessions["GO accessions"] = unique_accessions["accession"].map(ip2go_grouped)
unique_accessions.dropna(inplace=True)
unique_accessions.reset_index(drop=True, inplace=True)
unique_accessions.head()

,accession,protein_id,GO accessions
0,IPR000015,"[NP_415065.1, NP_414681.1, NP_415460.1, NP_417...","[GO:0015473, GO:0009297, GO:0016020]"
1,IPR000021,"[NP_416080.1, YP_026229.1, NP_414559.1, YP_025...",[GO:0016020]
2,IPR000023,[NP_418351.1],"[GO:0003872, GO:0006096]"
3,IPR000031,[NP_415056.1],[GO:0006189]
4,IPR000035,[NP_416572.1],"[GO:0003905, GO:0006281]"

Add namespaces

In [68]:
namespaces_grouped = (
    ip2go_df.dropna(subset=["namespace"])
    .groupby("Interpro accession")["namespace"]
    .apply(
        lambda x: list(set(x))[0]
    )  # Only select the first namespace, the order of appearance is cc -> mf -> bf
)

other_grouped = (
    ip2go_df.dropna(subset=["ribosome"])
    .groupby("Interpro accession")["ribosome"]
    .apply(
        lambda x: list(set(x))[0]
    )  # Only select the first namespace, the order of appearance is cc -> mf -> bf
)

unique_accessions["ribosome"] = unique_accessions["accession"].map(other_grouped)
unique_accessions["namespace"] = unique_accessions["accession"].map(namespaces_grouped)
unique_accessions.head()

,accession,protein_id,GO accessions,ribosome,namespace
0,IPR000015,"[NP_415065.1, NP_414681.1, NP_415460.1, NP_417...","[GO:0015473, GO:0009297, GO:0016020]",False,molecular_function
1,IPR000021,"[NP_416080.1, YP_026229.1, NP_414559.1, YP_025...",[GO:0016020],False,cellular_component
2,IPR000023,[NP_418351.1],"[GO:0003872, GO:0006096]",False,molecular_function
3,IPR000031,[NP_415056.1],[GO:0006189],False,biological_process
4,IPR000035,[NP_416572.1],"[GO:0003905, GO:0006281]",False,molecular_function

Explode by protein_name

In [69]:
namespace_df = unique_accessions.explode("protein_id").reset_index(drop=True)
namespace_df = namespace_df[["protein_id", "namespace", "ribosome"]].dropna()
namespace_df

           protein_id           namespace  ribosome
0         NP_415065.1  molecular_function     False
1         NP_414681.1  molecular_function     False
2         NP_415460.1  molecular_function     False
3         NP_417683.1  molecular_function     False
4      YP_009518785.1  molecular_function     False
...               ...                 ...       ...
11233     NP_416048.2  molecular_function     False
11234     NP_414766.1  molecular_function     False
11235     NP_416196.1  biological_process     False
11236     NP_416198.2  biological_process     False
11237     NP_416258.1  molecular_function     False

[11238 rows x 3 columns]

Load embeddings

In [70]:
embedding_df = pd.read_parquet("../data/embeddings/embeddings.parquet")
embedding_df

       protein_id                                          embedding
0      QXV77207.1  [32.183643, -92.390724, 101.33719, -34.524113,...
1      QXV77208.1  [34.715267, -31.693748, 17.047016, 35.399574, ...
2      QXV77209.1  [34.245323, -51.50776, 51.573765, 36.95897, 37...
3      QXV77210.1  [106.072784, -58.204082, 16.061924, 34.407246,...
4      QXV77211.1  [-86.80286, -35.08864, -18.125, 10.977238, 101...
...           ...                                                ...
20178  QXV81119.1  [-64.04541, -88.08594, 63.59424, 30.65918, 34....
20179  QXV81120.1  [-41.108994, -39.689022, 107.17606, 22.8125, -...
20180  QXV81121.1  [-89.57319, -147.06908, 47.314144, 20.608553, ...
20181  QXV81122.1  [-6.9336624, -30.915571, 17.984375, -16.881031...
20182  QXV81123.1  [-42.582077, -74.68407, 104.58105, 116.14423, ...

[20183 rows x 2 columns]

In [71]:
data_df = data_df.drop(columns=["sequence"])

In [72]:
final_df = namespace_df.merge(embedding_df, on="protein_id", how="left").merge(
    data_df,
    on="protein_id",
    how="left",
)
final_df = final_df.dropna()
final_df.to_parquet("../data/final_df.parquet")
final_df

,protein_id,namespace,ribosome,embedding,phage_id,description
0,NP_415065.1,molecular_function,False,"[-23.5926, -93.26165, 53.579185, 34.065807, 40...",NC_000913.3,putative fimbrial usher protein SfmD
1,NP_414681.1,molecular_function,False,"[7.8664575, -109.593315, 61.22201, 42.282944, ...",NC_000913.3,putative fimbrial usher protein HtrE
2,NP_415460.1,molecular_function,False,"[-2.407834, -99.97352, 60.042553, 48.969868, 5...",NC_000913.3,putative fimbrial usher protein ElfC
3,NP_417683.1,molecular_function,False,"[22.572277, -97.75069, 32.86291, 36.645363, 25...",NC_000913.3,putative fimbrial usher protein YhcD
4,YP_009518785.1,molecular_function,False,"[12.542888, -80.09453, 57.51416, -9.444865, 55...",NC_000913.3,fimbrial usher domain-containing protein YdeT
...,...,...,...,...,...,...
11233,NP_416048.2,molecular_function,False,"[-9.486918, -43.154552, 73.69865, -33.50775, 8...",NC_000913.3,DNA-binding transcriptional dual regulator MarA
11234,NP_414766.1,molecular_function,False,"[-26.077904, -22.599504, -38.980434, -16.47096...",NC_000913.3,DNA polymerase IV
11235,NP_416196.1,biological_process,False,"[-0.09374999, -17.330294, -32.915512, 74.86809...",NC_000913.3,Fe-S cluster scaffold complex subunit SufD
11236,NP_416198.2,biological_process,False,"[1.3834255, 7.7515087, 91.4114, 80.494934, 65....",NC_000913.3,Fe-S cluster scaffold complex subunit SufB
11237,NP_416258.1,molecular_function,False,"[15.652874, 37.505016, 66.20626, -20.168404, 2...",NC_000913.3,succinylglutamate desuccinylase

## Add cluster data
### Sequence clusters from mmseqs2

In [ ]:
seq_cluster_df = pd.read_csv(
    "../data/easy-cluster/result_cluster.tsv",
    sep="\t",
    names=["representative", "member"],
)

# Transform entries: MH550421.1_prot_AXN58042.1_1 -> AXN58042.1_1
seq_cluster_df["representative"] = seq_cluster_df["representative"].apply(
    lambda x: re.search(r"(?<=_prot_).*", x).group(0) if pd.notnull(x) else x
)
seq_cluster_df["member"] = seq_cluster_df["member"].apply(
    lambda x: re.search(r"(?<=_prot_).*", x).group(0) if pd.notnull(x) else x
)

# Collect all members in lists
seq_cluster_df = seq_cluster_df.groupby("representative")["member"].apply(list)
seq_cluster_df

representative
AXN58042.1_1    [AXN58042.1_1, AYD82598.1_1, QXV75388.1_112, Q...
AXN58043.1_2    [AXN58043.1_2, AYD82599.1_2, QXV75389.1_113, Q...
AXN58046.1_5    [AXN58046.1_5, AYD82602.1_5, QXV75392.1_116, Q...
AXN58047.1_6    [AXN58047.1_6, QXV83148.1_117, QXV85954.1_117,...
AXN58049.1_8    [AXN58049.1_8, AYD82605.1_8, QXV75395.1_119, Q...
                                      ...
b4571_2014                                           [b4571_2014]
b4579_353                                             [b4579_353]
b4580_364                                             [b4580_364]
b4582_1977                                           [b4582_1977]
b4623_4192                                           [b4623_4192]
Name: member, Length: 8864, dtype: object